SELECT * FROM FREE_RE;

SELECT F.MEM_NM, F.FREE_RE_CON, F.FREE_RE_DT
FROM (SELECT M.MEM_NM, F.FREE_RE_CON, TO_CHAR(F.FREE_RE_DT, 'YYYY-MM-DD') AS FREE_RE_DT,
        ROW_NUMBER()OVER(ORDER BY F.FREE_RE_NO DESC) AS RNUM 
        FROM FREE_RE F INNER JOIN MEM M
        ON F.MEM_NO = M.MEM_NO
        WHERE FREE_RE_DEL = 1
      ) F
WHERE F.RNUM BETWEEN 1 AND 3
;

SELECT COUNT(*) AS CNT
FROM FREE_RE F INNER JOIN MEM M
ON F.MEM_NO = M.MEM_NO
WHERE FREE_RE_DEL = 1
;
